version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: web
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    environment:
      NODE_ENV: 'development'
    volumes:
      - .:/expanse-api
    ports:
      - "3001:3001"
    depends_on:
      - db
      - clearweb
  clearweb:
    image: web
    build: .
    command: rm -rf /expanse-api/tmp/pids/server.pid
    volumes:
      - .:/expanse-api

