version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: web
    build: .
    command: ./bin/scripts/docker.rails_start.sh
    env_file:
      - '.env.docker'
    volumes:
      - .:/expanse-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
  webpacker:
    image: web
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/scripts/docker.webpack-dev-server.sh
    volumes:
      - .:/expanse-api
    ports:
      - '3035:3035'

